language: ruby
rvm:
- 2.3.5
before_script:
- bundle exec rake db:create
- bundle exec rake db:migrate
deploy:
  provider: heroku
  api_key:
    secure: Aow2nZFmkWpdytP7WQpMhsnw8LgSdk47oq9Ni6XFI7AVa/GFyiARb8n58/TQ367sq+gcfIHPCa8zDF0sNilh9S73l+RSJZNVJx70a0EazxUIufb/DsH0Ym8rZKG/R4Hv3jmFht12SysXE733pvY8RJeL19pqNeggBPENi5hKZSiO0u4lTDeszFkvHmNmGlNyAkA6cxxYN6OlWET5Sv4x4yPo5hE2hQRO/VXFd5VgHjDQ/sGCDO0kdJHxULW8paolcT1e10GjA8PaE8S8Uo9foR3uT37eD+PZDE9ZJS6WsuVcqw23gyLnN4S3UKqSy1ToManFD6DvtA6jOFBrGa2R5UnXOdcrFQFZuWua3nLp1ytpFHzoRy8AqLA7OJWxoYXEdZkR2k/ZcxcPW1WH8yI+z+BasvcG7t9KSxjEDFmnOF4Bgcl1TP+hODqVotOU0yUTnbUnpxRaYuX/nL2GkpHgMbnfihy6E/dehDnAPdc3Du5+IW0sKn4OVf8TLJpzYS08xm9OgIvM4cNc691diqHAada1vLU2d3Snyl/FxIFtYAWn/1fAPMlV6tCLFsdwt9c87Vk3Q5VjwHdGQjk/yfV8CXxx3vdXOU8qqigtRdFIrKcHIkAbIRZopTpIwg9xlciLYtnQvH2IntQlFWNjXSDKNYGg8K4iWMlnoaYXAyOxnHk=
  app: utbmworkv3
  on:
    repo: Skaopap/UTBM_WORK_V3
